# Generated by Django 5.0.4 on 2024-04-18 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_delete_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
