# Generated by Django 5.0.4 on 2024-04-30 19:55

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slice',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='slice',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание услуги'),
        ),
        migrations.AlterField(
            model_name='slice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
