# Generated by Django 5.0 on 2024-04-15 00:54

import apps.panel.utils
import django.core.validators
from django.db import migrations, models
import taggit.managers

class Migration(migrations.Migration):

    initial = True


    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to=apps.panel.utils.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx'])])),
                ('file_type', models.CharField(blank=True, help_text='Тип файла', max_length=50, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Размер файла в байтах', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Метки для поиска файла', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='panel.page')),
                ('slice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='panel.slice')),
            ],
        ),
    ]