# Generated by Django 5.0 on 2024-04-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.RemoveField(
            model_name='option',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='SEOData',
        ),
        migrations.RemoveField(
            model_name='set',
            name='items_content_type',
        ),
        migrations.RemoveField(
            model_name='template',
            name='parent_content_type',
        ),
        migrations.RemoveField(
            model_name='textcontent',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='slice',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\User\\Desktop\\Nest\\DEV\\mediaicons/'),
        ),
        migrations.AlterField(
            model_name='slice',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\User\\Desktop\\Nest\\DEV\\mediaimages/'),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.DeleteModel(
            name='TextContent',
        ),
    ]
