# Generated by Django 5.0 on 2024-04-15 00:54

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
from apps.panel.utils import get_upload_path, ALLOWED_EXTENSIONS
from taggit.managers import TaggableManager

class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, blank=True, null=True)),
                ('file', models.FileField(upload_to=get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=ALLOWED_EXTENSIONS)])),
                ('file_type', models.CharField(max_length=50, blank=True, null=True, help_text='Тип файла')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, help_text='Размер файла в байтах')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tags', TaggableManager(blank=True, help_text='Метки для поиска файла')),
                ('slice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='panel.slice', blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='panel.page', blank=True, null=True)),
            ],
        ),
    ]