# Generated by Django 5.0 on 2024-04-15 01:05

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='Untitled', max_length=255, null=True)),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('url', models.CharField(blank=True, default='new-page', max_length=255, null=True, unique=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('type', models.CharField(choices=[('cat', 'Category'), ('page', 'Page'), ('tpl', 'Template'), ('price', 'Price'), ('addsome', 'addsome')], default='cat', max_length=10)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='panel.page')),
            ],
        ),
        migrations.CreateModel(
            name='Slice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_main', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('price', models.FloatField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('keywords_block', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('parent_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slices', to='panel.page')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True, unique=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('type', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='personal', max_length=10)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='websites', to=settings.AUTH_USER_MODEL, verbose_name='Website Owner')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='parent_ws',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='panel.website'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['url', 'parent'], name='panel_page_url_ee927a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('url', 'parent'), ('url', 'parent_ws')},
        ),
    ]
