# Generated by Django 5.0 on 2024-04-15 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_media'),
        ('panel', '0002_page_slice_website_page_parent_ws_and_more'),
    ]

    operations = [
    ]
