# Generated by Django 5.0 on 2024-04-15 00:45

import apps.panel.utils
import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_media_seodata_alter_slice_icon_alter_slice_img_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='media',
            name='alt',
        ),
        migrations.AddField(
            model_name='media',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Размер файла в байтах', null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='file_type',
            field=models.CharField(blank=True, help_text='Тип файла', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='panel.page'),
        ),
        migrations.AddField(
            model_name='media',
            name='slice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='panel.slice'),
        ),
        migrations.AddField(
            model_name='media',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Метки для поиска файла', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=apps.panel.utils.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx'])]),
        ),
        migrations.AlterField(
            model_name='media',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),

    ]
