# Generated by Django 5.0 on 2024-04-15 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_remove_option_content_type_delete_seodata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='SEOData',
        ),
        migrations.RemoveField(
            model_name='set',
            name='items_content_type',
        ),
        migrations.RemoveField(
            model_name='template',
            name='parent_content_type',
        ),
        migrations.RemoveField(
            model_name='textcontent',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.DeleteModel(
            name='TextContent',
        ),
    ]
